#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Satoh-Narumi
# SPDX-License-Identifier: BSD-3-Clause
import sys  


ans = 0
for line in sys.stdin:
    try:
        ans += int(line)
    except:
        ans += int(line)

#変更点、なし

print(ans)


